### ISSUE TITLE
Template names not keeping directory

### ISSUE THREAD

**Issue by underkin** [bertramdev/handlebars-grails-asset-pipeline#4]
Hi,

It looks like in 2.0.0.2 the templates names do not keep the directory name.

For example, if I have 2 templates in:

assets/templates/template1.hbs
assets/templates/subdir/template1.hbs

In the Handlelbars object (Handlebars.templates),  bot the name of the templates are:

"template1"
"tempalte2"

instead of : 

"template1"
"subdir/template2"

This was working on a previous version of the plugin, but seems to be failing on 2.0.0.2

I have a minimal project I can attach if neede d.

Kind regards

**Comment by davydotcom** [comment]
Fixed in 2.1.3

**Comment by underkin** [comment]
Hi,

After updating the plugin, I'm getting this exception:

Looks related to templates with no folder at all.

Message: 
			Handlebars Engine compilation of handlebars to javascript failed.
			java.lang.NullPointerException: Cannot invoke method startsWith() on null object
			
    Line | Method
->>   79 | process              in asset.pipeline.handlebars.HandlebarsProcessor
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     87 | processedStream      in asset.pipeline.AbstractAssetFile
|    291 | fileContents . . . . in asset.pipeline.DirectiveProcessor
|     65 | serveUncompiledAsset in asset.pipeline.AssetPipeline
|     75 | doFilter . . . . . . in asset.pipeline.grails.AssetPipelineFilter
|   1145 | runWorker            in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                  in java.lang.Thread

**Comment by davydotcom** [comment]
Whoops! Released 2.1.4 and added test to make sure handlebars templates at the root path level don't cause this issue again in the future.

**Comment by underkin** [comment]
Thanks. Awesome!
