### ISSUE TITLE
Different versions of Handlebars in Dev and Prod

### ISSUE THREAD

**Issue by seb-grant** [bertramdev/handlebars-grails-asset-pipeline#5]
Since upgrading to the latest versions of Asset Pipeline (2.1.5) and Handlebars Asset Pipeline (2.1.4) plugins, I have noticed that two different versions of Handlebars are being used.

In dev the assets are compiled and rendered with 1.3.0, whereas at build time they are compiled with 2.0.0.

Is there a reason for this?

**Comment by denis111** [comment]
+1 why so?

**Comment by davydotcom** [comment]
shouldn't be the case with latest but ill double check

**Comment by davydotcom** [comment]
think i figured out why. Had to do with an order of operations with the binary dependency and grails plugin. I have since fixed in version `2.5.0` of the plugin which now comes prepackaged with handlebars version `4.0.2` you can also use your own version of handlebars. See the README for info

**Comment by davydotcom** [comment]
Scratch that fixed in `2.5.1`

**Comment by seb-grant** [comment]
Perfect, thanks David. Will check it out ASAP.
